### ISSUE TITLE
Extension doesn't work on Ubuntu 20.04 with GNOME 3.36

### ISSUE THREAD

**Issue by mystiquewolf** [vkrizan/NotificationCounter#1]
If [THIS](https://extensions.gnome.org/extension/1386/notification-counter/) is the published extension from this repo, then i have a bug report:

This extension shows "ERROR" and doesn't work on Ubuntu 20.04 focal fossa.

**Comment by vkrizan** [comment]
Yes it is.

Ubuntu 20.04 seems to have GNOME 3.36. I might look into it, but please feel free to post a patch.

Thank you.

**Comment by megamaced** [comment]
@vkrizan PLEASE make it work in GNOME 3.36! My workflow is now dead and there are no better alternatives then this one :-D

**Comment by vkrizan** [comment]
I'll get to it as soon as I can.

You might try a partial workaround: by disabling the notification popups. Once you'd get one, a bubble should appear, until you open the drawer.

**Comment by megamaced** [comment]
hero, working for me now
