### ISSUE TITLE
Support for Gnome 43

### ISSUE THREAD

**Issue by tiptr** [vkrizan/NotificationCounter#11]
The extension is incompatible with the current GNOME version 43. Could you please update it?
Thank you for the great work!

**Comment by vkrizan** [comment]
I'll try my best. Thank you for the report @tiptr

**Comment by yhz** [comment]
@tiptr I tried just updating supported shell versions in metadata.json - everything worked fine without errors.
@vkrizan Thanks for the extension!

**Comment by vkrizan** [comment]
Updated and uploaded to Gnome Extensions.

Cheers.

**Comment by tiptr** [comment]
Updated version works for me, thank you for the maintenance!
