### ISSUE TITLE
Transient notifications shouldn't count?

### ISSUE THREAD

**Issue by nekohayo** [vkrizan/NotificationCounter#15]
Some notifications are "transient", showing only for a few seconds before auto-deleting. For example, when you un-pin an application from the GNOME Shell dash.

While those notifications are shown, they increase the notification counter by 1 (so if there was 0 notifications, it creates the counter). However, wouldn't it make more sense for the counter not to increase when it's a transient notification, only when it's a notification that would stick around after being shown?

**Comment by vkrizan** [comment]
Hey @nekohayo,

Are those transient notifications (auto)deleted from the drawer? As far as I remember, if a notification is deleted (and there is a delete event), the counter should decrement. 

Can you please provide the version of you Gnome?

Thank you.

**Comment by vkrizan** [comment]
On 44.10, that I have, it behaves correctly with Do Not Disturb off.

```
notify-send --transient --expire-time=1000 Transient Notification
```

With DnD off, once the notification expires (or is dismissed by hovering over and out) the counter decreases.
With DnD on, the transient notification stays in the drawer until it is dismissed manually.

Are you expecting that it would disappear even with DnD is on or expecting that it would not be counted but still be present on the drawer? AFAIK the drawer (notification queue) behavior is Gnome's one.

**Comment by nekohayo** [comment]
Yeah, they do decrement after disappearing… but I wondered if it would make more sense for them to not increment the counter at all while DnD is off?

**Comment by vkrizan** [comment]
Yeah, I think that make sense. Currently only Normal priority and above are counted in. It would be possible to extend the condition to transient notifications (and DnD).

Reference:
https://wiki.gnome.org/Design/OS/Notifications#Transient
