### ISSUE TITLE
Update for GNOME 46 Support

### ISSUE THREAD

**Issue by Anifyuli** [vkrizan/NotificationCounter#16]
Hello, Mister.
I love this extension, and I hope this extension update for GNOME 46 support

**Comment by vkrizan** [comment]
I'll look into it as soon as I can. Usually there isn't any code change.

References: 
* https://gjs.guide/extensions/upgrading/gnome-shell-46.html

**Comment by vkrizan** [comment]
Unfortunately this needs a bit more time. I've discovered that it does not work well when DnD is turned on.

**Comment by Anifyuli** [comment]
Thanks for your hardworks, Bro
